### ISSUE TITLE
PSA: no longer working

### ISSUE THREAD

**Issue by Jxck-S** [artak-kirakosyan/airline_iata_icao_codes#5]
Tried to run this on 12/11/2023, just got empty lists.

**Comment by artak-kirakosyan** [comment]
@Jxck-S  thanks for pointing this out.
It's been a while since this was written.
Now the code works.
It writes each country data in ./data folder and then writes all country info in 1 file in the current directory.

Let me know if this doesn't work on your side :)

**Comment by Jxck-S** [comment]
Nice Job! I didn't expect you to get back so quickly. I haven't tested it but It's good to have. If you or anyone needs a simpler solution for just ICAO codes check out [https://www.mictronics.de/aircraft-database/export.php](https://www.mictronics.de/aircraft-database/export.php) the Indexed DB contains a JSON of ICAO opperator codes. Data looks like the following `"AAL":["American Airlines","United States","AMERICAN"]` I also made a scraper for airline logos for avcodes uk and others [Jxck-S/airline-logo-scraper](https://github.com/Jxck-S/airline-logo-scraper)
